class CreateOecCourseCodes < ActiveRecord::Migration
  def change
    create_table :oec_course_codes do |t|
      t.string :dept_name,        null: false
      t.string :catalog_id,       null: false
      t.string :dept_code,        null: false
      t.boolean :include_in_oec,  null: false

      t.timestamps
    end

    add_index :oec_course_codes, [:dept_name, :catalog_id], unique: true
    add_index :oec_course_codes, :dept_code

    reversible do |dir|
      dir.up do
        [
          'A,RESEC', '', 'MBARC', true,
          'AEROSPC', '', 'QLROT', false,
          'AFRICAM', '', 'SAAMS', false,
          'AFRKANS', '', 'HZGER', false,
          'AGR CHM', '', 'MEPMB', true,
          'AHMA', '', 'HTAHN', false,
          'ALTAIC', '', 'HGEAL', false,
          'AMERSTD', '', 'QHUIS', false,
          'ANTHRO', '', 'SZANT', false,
          'ARABIC', '', 'HNNES', false,
          'ARCH', '', 'DBARC', false,
          'ART', '', 'LQAPR', false,
          'ARMENI', '', 'LTSLL', false,
          'ASAMST', '', 'SBETH', false,
          'ASIANST', '', 'QIIAS', false,
          'AST', '', 'EDDNO', false,
          'ASTRON', '', 'PAAST', false,
          'BANGLA', '', 'HVSSA', false,
          'BIO ENG', '', 'EFBIO', false,
          'BIOLOGY', '1A', 'IMMCB', true,
          'BIOLOGY', '1AL', 'IMMCB', true,
          'BIOLOGY', '1B', 'IBIBI', true,
          'BIOLOGY', '1BL', 'IBIBI', true,
          'BIOPHY', '', 'IQBBB', false,
          'BOSCRSR', '', 'LTSLL', false,
          'BUDDSTD', '', 'HWBUD', false,
          'BULGARI', '', 'LTSLL', false,
          'BUS ADM', '', 'BAHSB', false,
          'CATALAN', '', 'LPSPP', true,
          'CELTIC', '', 'HSCAN', false,
          'CHEM', '', 'CCHEM', true,
          'CHICANO', '', 'SBETH', false,
          'CHINESE', '', 'HGEAL', false,
          'CHM ENG', '', 'CEEEG', false,
          'CIV ENG', '', 'EGCEE', false,
          'CLASSIC', '', 'LSCLA', false,
          'CMPBIO', '', 'BMCCB', false,
          'COG SCI', '', 'QHUIS', false,
          'COLWRIT', '', 'QKCWP', false,
          'COM LIT', '', 'HLCOM', false,
          'COMPBIO', '', 'OLGDD', false,
          'COMPSCI', '', 'EHEEC', false,
          'CRIT TH', '', 'CRTHE', false,
          'CRWRIT', '', 'English', false,
          'CUNEIF', '', 'HNNES', false,
          'CY PLAN', '', 'DCCRP', false,
          'CZECH', '', 'LTSLL', false,
          'DANISH', '', 'HSCAN', false,
          'DATASCI', '', 'MMIMS', true,
          'DEMOG', '', 'SDDEM', false,
          'DES INV', '', 'EDDNO', false,
          'DEV ENG', '', 'EGCEE', false,
          'DEV STD', '', 'QIIAS', false,
          'DEVP', '', 'MANRD', false,
          'DUTCH', '', 'HZGER', false,
          'EA LANG', '', 'HGEAL', false,
          'EAEURST', '', 'LTSLL', false,
          'ECON', '', 'SECON', true,
          'EDUC', '', 'EAEDU', false,
          'EECS', '', 'EHEEC', false,
          'EGYPT', '', 'HNNES', false,
          'EL ENG', '', 'EHEEC', false,
          'ENE,RES', '', 'MGERG', true,
          'ENGIN', '', 'EDDNO', false,
          'ENGLISH', '', 'HENGL', false,
          'ENV DES', '', 'DACED', false,
          'ENV SCI', '', 'MCESP', true,
          'ENVECON', '', 'MBARC', true,
          'EPS', '', 'PGEGE', true,
          'ESPM', '', 'MCESP', true,
          'ETH GRP', '', 'SBETH', false,
          'ETH STD', '', 'SBETH', false,
          'EURA ST', '', 'LTSLL', false,
          'EUST', '', 'LTSLL', false,
          'EWMBA', '', 'BAHSB', false,
          'FILIPN', '', 'HVSSA', false,
          'FILM', '', 'HUFLM', false,
          'FINNISH', '', 'HSCAN', false,
          'FOLKLOR', '', 'SZANT', false,
          'FRENCH', '', 'HFREN', false,
          'GEOG', '', 'SGEOG', false,
          'GERMAN', '', 'HZGER', false,
          'GMS', '', 'BUGMS', false,
          'GPP', '', 'QIIAS', false,
          'GREEK', '', 'LSCLA', false,
          'GSPDP', '', 'OLGDD', false,
          'GWS', '', 'SWOME', true,
          'HEBREW', '', 'HNNES', false,
          'HIN-URD', '', 'HVSSA', false,
          'HISTART', '', 'HARTH', false,
          'HISTORY', '', 'SHIST', false,
          'HMEDSCI', '', 'CPACA', false,
          'HUNGARI', '', 'LTSLL', false,
          'IAS', '', 'QIIAS', false,
          'ICELAND', '', 'HSCAN', false,
          'ILA', '', 'LPSPP', true,
          'IND ENG', '', 'EIIEO', false,
          'INFO', '', 'MMIMS', true,
          'INTEGBI', '', 'IBIBI', true,
          'IRANIAN', '', 'HNNES', false,
          'ISF', '', 'QHUIS', false,
          'ITALIAN', '', 'HITAL', false,
          'JAPAN', '', 'HGEAL', false,
          'JEWISH', '', 'KDCJS', false,
          'JOURN', '', 'DJOUR', false,
          'KHMER', '', 'HVSSA', false,
          'KOREAN', '', 'HGEAL', false,
          'L&S', '', 'QHUIS', false,
          'LAN PRO', '', 'OLGDD', false,
          'LATAMST', '', 'QIIAS', false,
          'LATIN', '', 'LSCLA', false,
          'LAW', '', 'CLLAW', false,
          'LD ARCH', '', 'DFLAE', false,
          'LEGALST', '', 'CLLAW', false,
          'LGBT', '', 'SWOME', true,
          'LINGUIS', '', 'SLING', true,
          'M E STU', '', 'QIIAS', false,
          'MALAY/I', '', 'HVSSA', false,
          'MAT SCI', '', 'EJMSM', false,
          'MATH', '', 'PMATH', true,
          'MBA', '', 'BAHSB', false,
          'MCELLBI', '', 'IMMCB', true,
          'MEC ENG', '', 'EKMEG', false,
          'MED ST', '', 'HPMED', false,
          'MEDIAST', '', 'QHUIS', false,
          'MFE', '', 'BAHSB', false,
          'MIL AFF', '', 'QLROT', false,
          'MIL SCI', '', 'QLROT', false,
          'MONGOLN', '', 'HGEAL', false,
          'MUSIC', '', 'HMUSC', false,
          'NAT RES', '', 'MANRD', false,
          'NATAMST', '', 'SBETH', false,
          'NAV SCI', '', 'QLROT', false,
          'NE STUD', '', 'HNNES', false,
          'NEUROSC', '', 'EUNEU', false,
          'NORWEGN', '', 'HSCAN', false,
          'NSE', '', 'OUNNI', false,
          'NUCENG', '', 'ELNUC', false,
          'NUSCTX', '', 'MDNST', true,
          'NWMEDIA', '', 'BTCNM', false,
          'OPTOM', '', 'BOOPT', false,
          'PACS', '', 'QIIAS', false,
          'PB HLTH', '', 'CPACA', false,
          'PERSIAN', '', 'HNNES', false,
          'PHDBA', '', 'BAHSB', false,
          'PHILOS', '', 'HCPHI', false,
          'PHYS ED', '', 'IPPEP', false,
          'PHYSICS', '', 'PHYSI', true,
          'PLANTBI', '', 'MEPMB', true,
          'POL SCI', '', 'SPOLS', true,
          'POLECON', '', 'QIIAS', false,
          'POLISH', '', 'LTSLL', false,
          'PORTUG', '', 'LPSPP', true,
          'PSYCH', '', 'SYPSY', true,
          'PUB POL', '', 'CFPPR', false,
          'PUNJABI', '', 'HVSSA', false,
          'RELIGST', '', 'QHUIS', false,
          'RHETOR', '', 'HRHET', false,
          'ROMANI', '', 'LTSLL', false,
          'RUSSIAN', '', 'LTSLL', false,
          'S ASIAN', '', 'HVSSA', false,
          'S,SEASN', '', 'HVSSA', false,
          'SANSKR', '', 'HVSSA', false,
          'SCANDIN', '', 'HSCAN', false,
          'SCMATHE', '', 'EAEDU', false,
          'SEASIAN', '', 'HVSSA', false,
          'SEMITIC', '', 'HNNES', false,
          'SLAVIC', '', 'LTSLL', false,
          'SOC WEL', '', 'CSDEP', false,
          'SOCIOL', '', 'SISOC', false,
          'SPANISH', '', 'LPSPP', true,
          'STAT', '', 'PSTAT', true,
          'STS', '', 'JYHST', false,
          'SWEDISH', '', 'HSCAN', false,
          'TAGALG', '', 'HVSSA', false,
          'TAMIL', '', 'HVSSA', false,
          'TELUGU', '', 'HVSSA', false,
          'THAI', '', 'HVSSA', false,
          'THEATER', '', 'HDRAM', false,
          'TIBETAN', '', 'HGEAL', false,
          'TURKISH', '', 'HNNES', false,
          'UGBA', '', 'BAHSB', false,
          'UGIS', '', 'QHUIS', false,
          'VIETNMS', '', 'HVSSA', false,
          'VIS SCI', '', 'BOOPT', false,
          'VIS STD', '', 'DBARC', false,
          'XMBA', '', 'BAHSB', false,
          'YIDDISH', '', 'HZGER', false
        ].each_slice(4) do |dept_name, catalog_id, dept_code, include_in_oec|
          Oec::CourseCode.create(
            dept_name: dept_name,
            catalog_id: catalog_id,
            dept_code: dept_code,
            include_in_oec: include_in_oec
          )
        end
      end

      dir.down do
        # All rows should be dropped.
      end
    end
  end
end
